///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace n11ExampleTestLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("d3681177-3ccd-4915-8080-ab5f3bc28218", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the n11ExampleTestLibraryRepository repository.
        /// </summary>
        public static n11ExampleTestLibraryRepository repo = n11ExampleTestLibraryRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            email = "";
            password = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("a45bf629-83a9-413a-b57e-ad1b94b2ba42")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("38d191c3-fc63-47b1-a192-82765e90a69e")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'GirişYapN11Com.Email' at 159;14.", repo.GirişYapN11Com.EmailInfo, new RecordItemIndex(0));
            repo.GirişYapN11Com.Email.DoubleClick("159;14");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'GirişYapN11Com.Email'.", repo.GirişYapN11Com.EmailInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.GirişYapN11Com.Email);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'GirişYapN11Com.Email'.", repo.GirişYapN11Com.EmailInfo, new RecordItemIndex(2));
            repo.GirişYapN11Com.Email.PressKeys("{Back}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'optiimtest1{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{LControlKey up}{RMenu up}gmail.com{Tab}' with focus on 'GirişYapN11Com.Email'.", repo.GirişYapN11Com.EmailInfo, new RecordItemIndex(3));
            repo.GirişYapN11Com.Email.PressKeys("optiimtest1{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{LControlKey up}{RMenu up}gmail.com{Tab}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0pt11mTEST'.", new RecordItemIndex(4));
            Keyboard.Press("0pt11mTEST");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GirişYapN11Com.LoginButton' at 40;15.", repo.GirişYapN11Com.LoginButtonInfo, new RecordItemIndex(5));
            repo.GirişYapN11Com.LoginButton.Click("40;15");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
