///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace n11ExampleTestLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the n11ExampleTestLibraryRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("102885e7-1cd9-49b0-adc8-bbcf4721a61a")]
    public partial class n11ExampleTestLibraryRepository : RepoGenBaseFolder
    {
        static n11ExampleTestLibraryRepository instance = new n11ExampleTestLibraryRepository();
        n11ExampleTestLibraryRepositoryFolders.GirişYapN11ComAppFolder _girişyapn11com;

        /// <summary>
        /// Gets the singleton class instance representing the n11ExampleTestLibraryRepository element repository.
        /// </summary>
        [RepositoryFolder("102885e7-1cd9-49b0-adc8-bbcf4721a61a")]
        public static n11ExampleTestLibraryRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public n11ExampleTestLibraryRepository() 
            : base("n11ExampleTestLibraryRepository", "/", null, 0, false, "102885e7-1cd9-49b0-adc8-bbcf4721a61a", ".\\RepositoryImages\\n11ExampleTestLibraryRepository102885e7.rximgres")
        {
            _girişyapn11com = new n11ExampleTestLibraryRepositoryFolders.GirişYapN11ComAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("102885e7-1cd9-49b0-adc8-bbcf4721a61a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GirişYapN11Com folder.
        /// </summary>
        [RepositoryFolder("9177b45d-1b57-4d6d-bc65-055f95bc9fa3")]
        public virtual n11ExampleTestLibraryRepositoryFolders.GirişYapN11ComAppFolder GirişYapN11Com
        {
            get { return _girişyapn11com; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class n11ExampleTestLibraryRepositoryFolders
    {
        /// <summary>
        /// The GirişYapN11ComAppFolder folder.
        /// </summary>
        [RepositoryFolder("9177b45d-1b57-4d6d-bc65-055f95bc9fa3")]
        public partial class GirişYapN11ComAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _cıkışyapInfo;
            RepoItemInfo _testInfo;
            RepoItemInfo _sueperfırsatlarInfo;

            /// <summary>
            /// Creates a new GirişYapN11Com  folder.
            /// </summary>
            public GirişYapN11ComAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GirişYapN11Com", "/dom[@domain='www.n11.com']", parentFolder, 30000, null, false, "9177b45d-1b57-4d6d-bc65-055f95bc9fa3", "")
            {
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "d84236d0-9abc-4c53-b481-448a76faaf4f");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//div[#'loginButton']", 30000, null, "958dceb4-a1ab-4a2b-8209-ca3319d5910f");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", ".//header[#'header']/div/div/div[2]/div[2]/div[2]//a[@innertext='Çıkış Yap']", 30000, null, "c4cb70de-6191-404c-8243-e0d398489867");
                _testInfo = new RepoItemInfo(this, "test", "element", 30000, null, "a48aafda-458b-4710-8e8d-3adaece77e56");
                _sueperfırsatlarInfo = new RepoItemInfo(this, "SueperFırsatlar", ".//header[#'header']/div/div/div[3]/nav/ul/?/?/a[@innertext='Süper Fırsatlar']", 30000, null, "233f819c-20a6-452d-9ed3-dab1d9ab57c9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9177b45d-1b57-4d6d-bc65-055f95bc9fa3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9177b45d-1b57-4d6d-bc65-055f95bc9fa3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("d84236d0-9abc-4c53-b481-448a76faaf4f")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("d84236d0-9abc-4c53-b481-448a76faaf4f")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("958dceb4-a1ab-4a2b-8209-ca3319d5910f")]
            public virtual Ranorex.DivTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("958dceb4-a1ab-4a2b-8209-ca3319d5910f")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("c4cb70de-6191-404c-8243-e0d398489867")]
            public virtual Ranorex.ATag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("c4cb70de-6191-404c-8243-e0d398489867")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }

            /// <summary>
            /// The test item.
            /// </summary>
            [RepositoryItem("a48aafda-458b-4710-8e8d-3adaece77e56")]
            public virtual Ranorex.Unknown test
            {
                get
                {
                    return _testInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The test item info.
            /// </summary>
            [RepositoryItemInfo("a48aafda-458b-4710-8e8d-3adaece77e56")]
            public virtual RepoItemInfo testInfo
            {
                get
                {
                    return _testInfo;
                }
            }

            /// <summary>
            /// The SueperFırsatlar item.
            /// </summary>
            [RepositoryItem("233f819c-20a6-452d-9ed3-dab1d9ab57c9")]
            public virtual Ranorex.ATag SueperFırsatlar
            {
                get
                {
                    return _sueperfırsatlarInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SueperFırsatlar item info.
            /// </summary>
            [RepositoryItemInfo("233f819c-20a6-452d-9ed3-dab1d9ab57c9")]
            public virtual RepoItemInfo SueperFırsatlarInfo
            {
                get
                {
                    return _sueperfırsatlarInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}