///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace n11ExampleTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the n11ExampleTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("2af8631f-b897-4940-9f77-268ce15218d4")]
    public partial class n11ExampleTestRepository : RepoGenBaseFolder
    {
        static n11ExampleTestRepository instance = new n11ExampleTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the n11ExampleTestRepository element repository.
        /// </summary>
        [RepositoryFolder("2af8631f-b897-4940-9f77-268ce15218d4")]
        public static n11ExampleTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public n11ExampleTestRepository() 
            : base("n11ExampleTestRepository", "/", null, 0, false, "2af8631f-b897-4940-9f77-268ce15218d4", ".\\RepositoryImages\\n11ExampleTestRepository2af8631f.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2af8631f-b897-4940-9f77-268ce15218d4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class n11ExampleTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}